import { createElement } from 'lwc';
import MeetingRooms from 'c/meetingRooms';

describe('c-meeting-rooms', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-meeting-rooms', {
            is: MeetingRooms
        });

        // Act
        document.body.appendChild(element);
        const allMeetingRooms= element.shadowRoot.querySelectAll("c-meeting-room");
        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(allMeetingRooms.length).toBe(7);
    });

    it("is meeting rooms title meeting room", ()=>{
        const element = createElement('c-meeting-rooms', {
            is: MeetingRooms
    });
    document.body.appendChild(element);
    const meetingRoomLightningCard= element.shadowRoot.querySelect("lightning-card");

    
        expect(meetingRoomLightningCard.title).toBe("Meeting Rooms");

});
});